# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = sc_sem
DESTDIR = ../../../lib
QT -= core gui
CONFIG += release shared

INCLUDEPATH += ../include
HEADERS += ../include/sc_sem.h
SOURCES += sc_sem.cpp

MOC_DIR += ../../../obj/common/sc_sem/.moc 
UI_DIR += ../../../obj/common/sc_sem/.ui
RCC_DIR += ../../../obj/common/sc_sem/.rcc 
