# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = sc_util
DESTDIR = ../../../lib
QT -= core gui

CONFIG += release shared

INCLUDEPATH += ../include
HEADERS += ../include/sc_util.h
SOURCES += sc_util.cpp

MOC_DIR += ../../../obj/common/sc_util/.moc 
UI_DIR += ../../../obj/common/sc_util/.ui
RCC_DIR += ../../../obj/common/sc_util/.rcc 
