# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = sdb_mysql
DESTDIR = ../../../lib
QT -= core gui

CONFIG += release shared

INCLUDEPATH += ../include
HEADERS += ../include/sdb_mysql.h
SOURCES += sdb_mysql.cpp

MOC_DIR += ../../../obj/database/mysql/.moc 
UI_DIR += ../../../obj/database/mysql/.ui
RCC_DIR += ../../../obj/database/mysql/.rcc 
