# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = sc_thread
DESTDIR = ../../../lib

CONFIG += debug static

HEADERS += ../include/sc_thread.h
SOURCES += sc_thread.cpp
DEFINES += UNICODE
MOC_DIR += ../../../obj/common/sc_thread/.moc 
UI_DIR += ../../../obj/common/sc_thread/.ui
RCC_DIR += ../../../obj/common/sc_thread/.rcc 
