# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = sc_console
DESTDIR = ../../../lib
QT -= core gui

CONFIG += release shared
INCLUDEPATH += ../include
HEADERS += ../include/sc_console.h
SOURCES += sc_console.cpp

MOC_DIR += ../../../obj/common/sc_console/.moc 
UI_DIR += ../../../obj/common/sc_console/.ui
RCC_DIR += ../../../obj/common/sc_console/.rcc 
